
export const NEW_AUTHOR_REQUEST = 'NEW_AUTHOR_REQUEST'
export const NEW_AUTHOR_SUCCESS = 'NEW_AUTHOR_SUCCESS'
export const NEW_AUTHOR_RESET = 'NEW_AUTHOR_RESET'
export const NEW_AUTHOR_FAIL = 'NEW_AUTHOR_FAIL'

export const DELETE_AUTHOR_REQUEST = 'DELETE_AUTHOR_REQUEST'
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS'
export const DELETE_AUTHOR_RESET = 'DELETE_AUTHOR_RESET'
export const DELETE_AUTHOR_FAIL = 'DELETE_AUTHOR_FAIL'
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const UPDATE_AUTHOR_REQUEST = 'UPDATE_AUTHOR_REQUEST'
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS'
export const UPDATE_AUTHOR_RESET = 'UPDATE_AUTHOR_RESET'
export const UPDATE_AUTHOR_FAIL = 'UPDATE_AUTHOR_FAIL'

export const ALL_AUTHORS_REQUEST = "ALL_AUTHORS_REQUEST"
export const ALL_AUTHORS_SUCCESS = "ALL_AUTHORS_SUCCESS"
export const ALL_AUTHORS_FAIL = "ALL_AUTHORS_FAIL"